routes/web.php
<?php

use App\Http\Controllers\CategoryConroller;
use App\Models\Category;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('categories', CategoryConroller::class);

app/Models/Category.php
<?php

namespace App\Models;

use App\Exceptions\BusinessException;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'parent_id'];

    /**
     * @return BelongsTo
     */
    public function parent(): BelongsTo
    {
        return $this->belongsTo(Category::class, 'parent_id');
    }
    
    /**
     * @param Category|null $category
     */
    public function attachParent(Category|null $category): void
    {
        if (is_null($category)) {
            $this->setParentId($category);
        }
        $child = $this->children?->where('id', $category->getKey() )->first();
        
        if ($child) {
            throw new BusinessException('The category is a child.');
        }

        $this->setParentId($category->getKey());
    }

    /**
     * @return HasMany
     */
    public function children(): HasMany
    {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    /**
     * @param bool
     */
    public function hasChildren(): bool
    {
        return (bool) $this->children->count();
    }

    /**
     * @return null|string
     */
    public function getName(): ?string 
    {
        return $this->name;
    }

    /**
     * @param string
     */
    public function setName(string $name): void 
    {
        $this->name = $name;
    }

    /**
     * @param null|int
     */
    public function setParentId(int|null $parentId): void 
    {
        $this->parent_id = $parentId ? $parentId : 0;
    }
}   

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CategoryConroller.php
<?php

namespace App\Http\Controllers;

use App\Exceptions\BusinessException;
use App\Http\Requests\SaveCategoryRequest;
use App\Models\Category;
use Illuminate\Support\Facades\View;

class CategoryConroller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();

        return View::make('categories.list', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Category $category)
    {
        $categories = Category::all();

        return View::make('categories.form', compact('category', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  SaveCategoryRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SaveCategoryRequest $request)
    {
        Category::create($request->validated());
        
        return back()->with('message', 'Created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return View::make('categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $categories = Category::all();

        return View::make('categories.form', compact('category', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  SaveCategoryRequest  $request
     * @param  Category $category
     * @return \Illuminate\Http\Response
     */
    public function update(SaveCategoryRequest $request, Category $category)
    {   
        try {
            $parent = Category::find($request->parent_id);
            $category->setName($request->name);
            $category->attachParent($parent);
            $category->save();
            return back()->with('message', 'Updated.');
        } catch(BusinessException $e) {
            return back()->withInput()->withErrors(['message' => $e->getMessage()]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        if ($category->hasChildren()) {
            return back()->withErrors('message', 'The category has children.');       
        }

        $category->delete();
        return back()->with('message', 'Deleted.');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task-category</title>
</head>
<body>
    <nav>
        <a href=""></a>
    </nav>
    @yield('content')
</body>
</html>

resources/views/categories/form.blade.php
@extends('app')

@section('content')
    <div>
        @foreach($errors->all() as $message)
            <p>{{ $message }}</p>
        @endforeach
    </div>
    <div>
        @if(session()->has('message'))
            <p>{{ session()->get('message') }}</p>
        @endif
    </div>
    @if($category->exists)
        <form action="{{ route('categories.update', $category->getKey()) }}" method="POST">
        @method('PUT')
    @else
        <form action="{{ route('categories.store') }}" method="POST">
    @endif
        @csrf

        <select name="parent_id">
            <option value="">Select parent category</option>
            @foreach($categories as $selectionCategory)
                <option @if($category->parent?->getKey() == $selectionCategory->getKey()) selected @endif 
                    value="{{ $selectionCategory->getKey() }}">{{ $selectionCategory->getName() }}</option>
            @endforeach
        </select>
        <input type="text" name="name" value="{{ old('name', $category->exists ? $category->getName() : '') }}">
        <input type="submit" value="Send">
    </form>
@endsection

resources/views/categories/list.blade.php
@extends('app')

@section('content')
    <ul>
       @foreach($categories as $category)
            <li>
                <a href="{{ route('categories.show', $category->getKey()) }}">{{ $category->getName() }}</a>
            </li>
       @endforeach
    </ul>
@endsection

resources/views/categories/show.blade.php
@extends('app')

@section('content')
    <h2>
        {{ $category->getName() }}
    </h2>
@endsection